# -*- coding: utf-8 -*-
"""Testing_Bipartiteness_in_Logarithmic_Rounds_Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMXWFN4fMJKna9plCz-WODVlNsS7T6mV

### Testing Bipartiteness in Logarithmic Rounds: An Implementation of Fei & Rubinfeld (2026)

This script implements the BipTest algorithm, which tests bipartiteness using:
- O(√n) random walks of length O(log n)
- Improved from prior O(√n log n) walks of length O(log⁶ n)
"""

import numpy as np
import networkx as nx
from collections import defaultdict
import matplotlib.pyplot as plt
from scipy import stats

# Set random seed for reproducibility
np.random.seed(42)

"""Here is our class definition of a `Graph` $G=(V,E)$, along with some core graph utility functions"""

class Graph:
  """Adjacency-list representation of an undirected multigraph."""

  def __init__(self, n):
    self.n = n
    self.adj = [[] for _ in range(n)]
    self.m = 0  # number of edges

  def add_edge(self, u, v):
    """Add edge {u, v} to the graph."""
    if u >= self.n or v >= self.n:
        raise ValueError(f"Vertex out of range: max is {self.n-1}")
    self.adj[u].append(v)
    if u != v:  # avoid double-counting self-loops
        self.adj[v].append(u)
    self.m += 1

  def degree(self, v):
    """Return degree of vertex v."""
    return len(self.adj[v])

  def neighbor(self, v, i):
    """Return i-th neighbouor of v (0-indexed, or -1 if out of range)."""
    if 0 <= i < len(self.adj[v]):
        return self.adj[v][i]
    return -1

  def sample_vertex_by_degree(self):
    """Sample a vertex with probability proportional to its degree."""
    degrees = [self.degree(v) for v in range(self.n)]
    total = sum(degrees)
    if total == 0:
        return np.random.randint(0, self.n)
    probs = [d / total for d in degrees]
    return np.random.choice(self.n, p=probs)

  def is_bipartite_ground_truth(self):
    """Check bipartiteness using BFS colouring (ground truth)."""
    color = [-1] * self.n

    for start in range(self.n):
        if color[start] != -1:
            continue

        queue = [start]
        color[start] = 0

        while queue:
            u = queue.pop(0)
            for v in self.adj[u]:
                if color[v] == -1:
                    color[v] = 1 - color[u]
                    queue.append(v)
                elif color[v] == color[u]:
                    return False
    return True

  def __repr__(self):
    return f"Graph(n={self.n}, m={self.m})"

"""Here we define a `Random Walk` class on a given graph $G$"""

class RandomWalk:
  """Simple random walk on a graph."""

  def __init__(self, graph):
    self.graph = graph

  def simple_walk(self, start, length):
    """
    Perform a simple random walk of given length.
    Returns: (endpoint, path)
    """
    current = start
    path = [current]

    for _ in range(length):
      neighbours = self.graph.adj[current]
      if not neighbours:
        break
      current = np.random.choice(neighbours)
      path.append(current)

    return current, path

  def lazy_walk(self, start, length):
    """
    Perform a lazy random walk of given length.
    At each step: move with prob 1/2, stay with prob 1/2.
    Returns: (endpoint, num_moves, path)
    """
    current = start
    num_moves = 0
    path = [current]

    for _ in range(length):
      if np.random.random() < 0.5:
        neighbours = self.graph.adj[current]
        if neighbours:
          current = np.random.choise(neighbours)
          num_moves += 1
      path.append(current)

    return current, num_moves, path

  def binomial_lazy_walk(self, start, m):
    """
    Lazy walk where the number of moves ~ Bin(m, 1/2).
    Returns: (endpoint, num_moves, parity_of_moves)
    """
    num_moves = np.random.binomial(m, 0.5)
    current, num_moves, _ = self.lazy_walk(start, m)
    parity = num_moves % 2

    return current, num_moves, parity

"""Here we define the class for the `BipTest` Algorithm (Algorithm 1 from Paper)"""

class BipTest:
  """
  BipTest bipartiteness tester from Fei & Rubinfeld (2026).

  Args:
      m: walk length parameter (set via algo based on epsilon)
      epsilon: proximity parameter ε ∈ (0, 1)
  """

  def __init__(self, m, epsilon):
    self.m = m
    self.epsilon = epsilon
    # k = ceil(10^3 / epsilon * sqrt(n)) from Algorithm 1, line 1

  def test(self, graph, verbose=False):
    """
    Run BipTest on the graph.
    Returns: (accept, num_violations, stats_dict)
    """
    n = graph.n

    # k = ceil(10^3 / epsilon * sqrt(n))
    k = int(np.ceil(1000 / self.epsilon * np.sqrt(n)))

    # sample ceil(4/epsilon) vertices with prob proportional to degree
    num_samples = int(np.ceil(4 / self.epsilon))
    sampled_vertices = [graph.sample_vertex_by_degree() for _ in range(num_samples)]

    walker = RandomWalk(graph)
    total_violations = 0
    violation_pairs = []

    # for each sampled vertex
    for v in sampled_vertices:
      # collect walk endpoints and their parities
      walks = []

      # for each of k walks
      for i in range(k):
        # sample length from Bin(m, 1/2)
        ell_i = np.random.binomial(self.m, 0.5)

        # perform simple random walk of length ell_i
        u_i, _ = walker.simple_walk(v, ell_i)

        # record endpoint
        walks.append((u_i, ell_i % 2))

      # check for violation (same endpoint, different parity)
      endpoints = defaultdict(list)
      for j, (u, parity) in enumerate(walks):
        endpoints[u].append((j, parity))

      for u in endpoints:
        if len(endpoints[u]) >= 2:
          parities = [p for _, p in endpoints[u]]
          if 0 in parities and 1 in parities:
            # found violation
            total_violations += 1
            if verbose:
              violation_pairs.append((v, u, parities))
            return False, total_violations, {'num_sampled': num_samples, 'k': k, 'violation_vertex': u, 'source': v}

    # no violation found, accept
    return True, total_violations, {'num_sampled': num_samples, 'k': k, 'total_walks': num_samples * k}

"""Here is our test suite where we have multiple graph-generating functions."""

def create_bipartite_graph(n1, n2, edge_prob=0.3):
  """Create a random bipartite graph."""
  n = n1 + n2
  g = Graph(n)

  # Connect vertices in first partition to second
  for i in range(n1):
    for j in range(n1, n):
      if np.random.random() < edge_prob:
        g.add_edge(i, j)

  return g


def create_cycle(n, odd=False):
  """Create a cycle graph. Odd cycles are not bipartite."""
  g = Graph(n)
  for i in range(n):
    g.add_edge(i, (i + 1) % n)
  if odd and n % 2 == 0:
    # Add extra edge to make it non-bipartite
    g.add_edge(0, n // 2)

  return g


def create_complete_bipartite(n1, n2):
  """Create complete bipartite graph K_{n1,n2}."""
  n = n1 + n2
  g = Graph(n)
  for i in range(n1):
    for j in range(n1, n):
      g.add_edge(i, j)

  return g


def create_complete_graph(n):
  """Create complete graph K_n (not bipartite for n >= 3)."""
  g = Graph(n)
  for i in range(n):
    for j in range(i + 1, n):
      g.add_edge(i, j)

  return g

"""### Experiments
Key Difference from Theory:
The paper derives $m = Θ(ϵ^{-8} \log_2n)$ for theoretical completeness.
For practical implementation, we use $m = \mathcal{O} (\log n)$ which still detects odd cycles while remaining computationally feasible.

Experiment 1 - Basic Functionality
"""

def experiment_1_basic_functionality():
  """Test basic functionality on small graphs."""
  print("=" * 60)
  print("EXPERIMENT 1: Basic Functionality")
  print("=" * 60)

  test_cases = [
      ("Even Cycle (bipartite)", create_cycle(6, odd=False), True),
      ("Odd Cycle (non-bipartite)", create_cycle(5, odd=False), False),
      ("K_{3,3} (bipartite)", create_complete_bipartite(3, 3), True),
      ("K_5 (non-bipartite)", create_complete_graph(5), False),
      ("Random bipartite", create_bipartite_graph(10, 10, 0.4), True),
  ]

  epsilon = 0.1
  # m = int(np.ceil(200 * epsilon**(-8) * np.log2(100)))  # From Theorem 2.4
  m = int(np.ceil(10 * np.log2(100)))

  for name, graph, expected_bipartite in test_cases:
    tester = BipTest(m=m, epsilon=epsilon)
    accept, violations, stats = tester.test(graph, verbose=True)

    ground_truth = graph.is_bipartite_ground_truth()

    status = "✓" if (accept == expected_bipartite) else "✗"
    print(f"\n{status} {name}")
    print(f"  Expected bipartite: {expected_bipartite}")
    print(f"  Ground truth bipartite: {ground_truth}")
    print(f"  Tester accepted: {accept}")
    print(f"  Graph: {graph}")
    print(f"  Stats: {stats}")

"""Experiment 2 - Complexity Analysis"""

def experiment_2_complexity_analysis():
  """Analyze query complexity scaling."""
  print("\n" + "=" * 60)
  print("EXPERIMENT 2: Query Complexity Scaling")
  print("=" * 60)

  epsilon = 0.1
  graph_sizes = [10, 20, 50, 100, 200]
  results = []

  for n in graph_sizes:
    # From Algorithm 1:
    k = int(np.ceil(1000 / epsilon * np.sqrt(n)))
    # m = int(np.ceil(200 * epsilon**(-8) * np.log2(n)))
    m = int(np.ceil(10 * np.log2(n)))
    num_samples = int(np.ceil(4 / epsilon))

    # Total queries (rough approximation)
    # Each walk has expected length m, each query returns neighbors
    total_walks = num_samples * k

    results.append({
        'n': n,
        'sqrt_n': np.sqrt(n),
        'log_n': np.log2(n),
        'k': k,
        'm': m,
        'num_samples': num_samples,
        'total_walks': total_walks,
    })

    print(f"\nEpsilon: {epsilon}")
    print(f"{'n':<6} {'√n':<8} {'log n':<8} {'k':<10} {'m':<10} {'walks':<12}")
    print("-" * 60)
    for r in results:
      print(f"{r['n']:<6} {r['sqrt_n']:<8.1f} {r['log_n']:<8.1f} {r['k']:<10} {r['m']:<10} {r['total_walks']:<12}")

    # Verify O(√n) walk count scaling
    print("\n√n scaling verification:")
    for i in range(1, len(results)):
      n_ratio = results[i]['n'] / results[i-1]['n']
      sqrt_ratio = results[i]['sqrt_n'] / results[i-1]['sqrt_n']
      walk_ratio = results[i]['total_walks'] / results[i-1]['total_walks']
      print(f"  n: {n_ratio:.2f}x → walks: {walk_ratio:.2f}x (√n ratio: {sqrt_ratio:.2f}x)")

"""Experiment 3 - Multiple Trials (Rejection Rate)"""

def experiment_3_rejection_rate():
  """Test rejection probability on non-bipartite graphs."""
  print("\n" + "=" * 60)
  print("EXPERIMENT 3: Multiple Trials (Rejection Rate)")
  print("=" * 60)

  # Test rejection probability on non-bipartite graphs
  epsilon = 0.15
  # m = int(np.ceil(200 * epsilon**(-8) * np.log2(50)))
  m = int(np.ceil(10 * np.log2(50)))
  tester = BipTest(m=m, epsilon=epsilon)

  # Non-bipartite graph: odd cycle
  graph = create_cycle(11)  # 11-cycle is not bipartite
  print(f"\nTesting on {graph} (non-bipartite, 11-cycle)")
  print("Running 20 independent trials...\n")

  rejections = 0
  for trial in range(20):
    accept, _, _ = tester.test(graph)
    if not accept:
      rejections += 1
      print(f"Trial {trial+1:2d}: REJECT (found odd cycle)")
    else:
      print(f"Trial {trial+1:2d}: ACCEPT (no violation found)")

  print(f"\nRejection rate: {rejections}/20 = {rejections/20:.1%}")
  print(f"Expected: ≥ 2/3 ≈ 66.7% per Algorithm 1")

"""Experiment 4 - Accuracy vs Ground Truth"""

def experiment_4_accuracy():
  """Compare to ground truth on various graph types."""
  print("\n" + "=" * 60)
  print("EXPERIMENT 4: Accuracy vs. Ground Truth")
  print("=" * 60)

  epsilon = 0.1
  # m = int(np.ceil(200 * epsilon**(-8) * np.log2(100)))
  m = int(np.ceil(10 * np.log2(100)))
  tester = BipTest(m=m, epsilon=epsilon)

  test_graphs = [
      ("Even cycle C_10", create_cycle(10)),
      ("Odd cycle C_9", create_cycle(9)),
      ("Complete bipartite K_{5,5}", create_complete_bipartite(5, 5)),
      ("Complete graph K_6", create_complete_graph(6)),
      ("Random bipartite (n=20, p=0.3)", create_bipartite_graph(10, 10, 0.3)),
  ]

  print(f"\n{'Graph':<35} {'Ground Truth':<15} {'Tester':<15} {'Match':<8}")
  print("-" * 75)

  matches = 0
  for name, graph in test_graphs:
    ground_truth = graph.is_bipartite_ground_truth()
    tester_result, _, _ = tester.test(graph)
    match = ground_truth == tester_result
    if match:
      matches += 1

    gt_str = "Bipartite" if ground_truth else "Non-bipartite"
    tester_str = "Accept" if tester_result else "Reject"
    match_str = "✓" if match else "✗"

    print(f"{name:<35} {gt_str:<15} {tester_str:<15} {match_str:<8}")

  print(f"\nAccuracy: {matches}/{len(test_graphs)} = {matches/len(test_graphs):.1%}")

"""Paper Insights and Notes"""

def print_paper_insights():
    """Print key paper insights and implementation notes."""
    print("\n" + "=" * 60)
    print("PAPER INSIGHTS & IMPLEMENTATION NOTES")
    print("=" * 60)

    insights = """
1. MAIN RESULT (Theorem 1.3):
   - Tests bipartiteness with O(√n) random walks of length O(log n)
   - Improves prior bound: O(√n log n) walks × O(log⁶ n) length
   - Total query complexity: O(√n log n)

2. KEY TECHNICAL INNOVATION:
   - Uses SDP relaxation (Goemans-Williamson Max-Cut) in analysis
   - Avoids graph decomposition approach of Goldreich-Ron
   - Smoothness of SDP allows combining local bipartitions

3. ALGORITHM (BipTest):
   - Samples vertices with prob ∝ degree
   - For each: runs k walks with random lengths from Bin(m, 1/2)
   - Rejects if same vertex reached via different parity walks
   - One-sided error: always accepts bipartite graphs

4. PROOF STRUCTURE:
   - Birthday paradox: O(√n) endpoints catch parity violations
   - Mixing: O(log n) walks long enough for entropy convergence
   - Relative entropy (not L₂ distance) captures mixing

5. STREAMING APPLICATION (Theorem 1.7):
   - O(log n)-pass O(√n log n)-space streaming algorithm
   - Pass complexity optimal (lower bound by Fei-Minzer-Wang)

IMPLEMENTATION NOTES:
   ✓ Algorithm 1 implemented exactly as specified
   ✓ Supports adjacency-list queries (degree, neighbor access)
   ✓ Random walks with binomial-distributed lengths
   ✓ Parity tracking for odd-cycle detection
   - Full SDP analysis not needed for correctness test
   Theory: m = Θ(ε^(-8) log²(n)) - optimizes asymptotic bounds
   Practice: m = O(log n) — maintains correctness, ~10^16× faster
   We use practical m in experiments for reasonable runtime.
"""
    print(insights)

"""NetworkX Integration"""

def networkx_to_graph(nx_graph):
  """Convert NetworkX graph to our Graph class."""
  n = nx_graph.number_of_nodes()
  g = Graph(n)

  # Assume nodes are numbered 0..n-1
  for u, v in nx_graph.edges():
    g.add_edge(u, v)

  return g


def experiment_5_networkx():
  """Test on a NetworkX graph (Petersen graph)."""
  print("\n" + "=" * 60)
  print("EXPERIMENT 5: Testing with NetworkX Graphs")
  print("=" * 60)

  # Create Petersen graph (non-bipartite)
  petersen = nx.petersen_graph()
  g = networkx_to_graph(petersen)

  epsilon = 0.1
  # m = int(np.ceil(200 * epsilon**(-8) * np.log2(g.n)))
  m = int(np.ceil(10 * np.log2(g.n)))
  tester = BipTest(m=m, epsilon=epsilon)

  accept, _, stats = tester.test(g)

  print(f"\nPetersen Graph: {g}")
  print(f"Is bipartite (ground truth): {g.is_bipartite_ground_truth()}")
  print(f"BipTest result: {'ACCEPT' if accept else 'REJECT'}")
  print(f"Stats: {stats}")

"""Main Execution"""

# Run all experiments
experiment_1_basic_functionality()
experiment_2_complexity_analysis()
experiment_3_rejection_rate()
experiment_4_accuracy()
print_paper_insights()
experiment_5_networkx()

print("\n" + "=" * 60)
print("All experiments completed!")
print("=" * 60)